### ISSUE TITLE
Support golang 1.9

### ISSUE THREAD

**Issue by siebertm** [codeclimate-community/codeclimate-golint#18]
We have a go 1.9 project which uses type aliases. The current codeclimate-golint version does not seem to support golang 1.9:

```
Could not lint file: /code/hl7/hl7.go
Error /code/hl7/hl7.go:13:14: expected type, found '=' (and 4 more errors)
```

The respective line is

```go
type Segment = hl7.Segment
```

Can the engine be updated to support that?

**Comment by wfleming** [comment]
Hi @siebertm,

Thanks for the report. We've just released a new version of this plugin that should have an updated version of `golint`: if you're using codeclimate.com you should be getting analysis from the new version already. If you're using our CLI, you'll need to run `codeclimate engines:install` to get the new version.

Please let me know if the new version  is working better for you.

**Comment by levinalex** [comment]
#19 does not fix this issue, because to support Go 1.9, golint has to be _compiled with_ Go 1.9. (and `alpine:3.4` does not ship with Go 1.9. (looks like even alpine 3.6 only has Go 1.8.3)

**Comment by levinalex** [comment]
there is [`golang:1.9-alpine`](https://github.com/docker-library/golang/blob/master/1.9/alpine3.6/Dockerfile), which might work as a base image.
